@startuml
participant ":Cart" as Cart
participant ":CartItem" as CartItem
participant ":Product" as Product

[-> Cart : getPrice()
Cart -> CartItem : [*] getPrice()
CartItem -> Product : getPrice()
@enduml
